### PR TITLE
Dean/open graph metadata

### LINKED ISSUE #21: Update thumbnails and opengraph metadata for state pages
Each state page should really have customized opengraph metadata for social sharing. Basically, it should say "How to vote early in Minnesota" instead of a general "How to early vote" message.

### PR DESCRIPTION
**Pull request by deanputney**
Here is how to make the share images for each state:

1. Load the homepage.
1. Open the web inspector and turn on mobile mode.
1. Set to responsive. Set dimensions to 542 x 304.
1. Modify the `.hero` element to have `height: 100vh;`. This fills the viewport.
1. Use [Nimbus Screenshot](https://chrome.google.com/webstore/detail/nimbus-screenshot-screen/bpconcjcammlapcogcnnelfmaeghhagj/related?hl=en) to take a screenshot of the visible area of the page.
1. In the Nimbus settings, **uncheck** "Keep original resolution (for Retina)". This makes the screenshot retina resolution instead of screen resolution.

### CODE REVIEW

**Comment by deanputney** [comment]
I don't particularly want to deal with loading all the images into React at the moment to actually put them in the share URL. @kofron if you're up for it in the morning, go nuts. Once that's done this closes the share metadata issue #21.

**Review by kofron — APPROVED** [review]
LGTM

**Comment by kofron** [comment]
I'll take care of the images right now

**Comment by kofron** [comment]
I have performed the following dark magic:

```
ls src/images/state-shares/* | sed -e 's/\// /g' -e 's/\./ /g' -e 's/-//g' | awk '{print "import " $(NF-1)"ShareImage from '\''../images/site-shares/" $(NF-1)".png'\'';" }'
```

**Comment by kofron** [comment]
Except that won't work.  Not entirely sure how to do this actually, we should talk about it

**Comment by deanputney** [comment]
Looks like we're in good shape now. The images appear to be writing properly to the HTML.

**Pull request merged**
